# Generated by Django 4.2.1 on 2023-05-28 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='autor',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='ubicacion',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='job')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categorias', models.ManyToManyField(to='jobs.categorias')),
            ],
            options={
                'verbose_name': 'empleo',
                'verbose_name_plural': 'empleos',
            },
        ),
    ]
